import { useQuery } from "@tanstack/react-query";
import { AlertTriangle, Database, ShieldCheck } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

type SearchEvent = {
  id: string;
  searchTerm: string;
  serviceType: string | null;
  searchContext: string | null;
  createdAt: string | null;
};

type ErrorEvent = {
  id: string;
  errorType: string;
  errorMessage: string;
  severity: string;
  createdAt: string | null;
};

async function getQaData<T>(path: string): Promise<T> {
  const response = await fetch(path, { credentials: "include" });
  if (!response.ok) throw new Error(response.status === 403 ? "QA access is not enabled for this account." : "Unable to load QA data.");
  return response.json();
}

function formatDate(value: string | null) {
  return value ? new Date(value).toLocaleString() : "Unknown time";
}

export default function QaAdminConsole() {
  const searches = useQuery({
    queryKey: ["/api/qa/admin/search-analytics"],
    queryFn: () => getQaData<SearchEvent[]>("/api/qa/admin/search-analytics?limit=50"),
  });
  const errors = useQuery({
    queryKey: ["/api/qa/admin/errors"],
    queryFn: () => getQaData<ErrorEvent[]>("/api/qa/admin/errors?limit=50"),
  });

  const accessError = searches.error || errors.error;

  return (
    <main className="mx-auto max-w-6xl space-y-6 px-4 py-8">
      <section className="rounded-lg border border-amber-400 bg-amber-50 p-5 text-amber-950">
        <div className="flex items-start gap-3">
          <ShieldCheck className="mt-0.5 h-6 w-6 shrink-0" aria-hidden="true" />
          <div>
            <h1 className="text-xl font-semibold">TEST — QA Read-only Admin Console</h1>
            <p className="mt-1 text-sm">
              This view is restricted to QA fixture data. It cannot manage users, billing, messaging, settings, or any real production record.
            </p>
          </div>
        </div>
      </section>

      {accessError ? (
        <section className="rounded-lg border border-destructive/40 bg-destructive/5 p-5 text-sm text-destructive">
          {accessError instanceof Error ? accessError.message : "QA access could not be verified."}
        </section>
      ) : null}

      <section className="grid gap-6 lg:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2"><Database className="h-5 w-5" />QA search analytics</CardTitle>
            <CardDescription>Only events generated by labeled QA accounts appear here.</CardDescription>
          </CardHeader>
          <CardContent>
            {searches.isLoading ? <p className="text-sm text-muted-foreground">Loading QA search events…</p> : null}
            {!searches.isLoading && searches.data?.length === 0 ? <p className="text-sm text-muted-foreground">No QA search events yet.</p> : null}
            <ul className="space-y-3">
              {searches.data?.map((event) => (
                <li key={event.id} className="rounded-md border p-3 text-sm">
                  <p className="font-medium">{event.searchTerm}</p>
                  <p className="mt-1 text-muted-foreground">{event.serviceType || "Any service"} · {event.searchContext || "Unknown context"}</p>
                  <p className="mt-1 text-xs text-muted-foreground">{formatDate(event.createdAt)}</p>
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2"><AlertTriangle className="h-5 w-5" />QA developer diagnostics</CardTitle>
            <CardDescription>Only error logs generated by labeled QA accounts appear here.</CardDescription>
          </CardHeader>
          <CardContent>
            {errors.isLoading ? <p className="text-sm text-muted-foreground">Loading QA error logs…</p> : null}
            {!errors.isLoading && errors.data?.length === 0 ? <p className="text-sm text-muted-foreground">No QA error logs yet.</p> : null}
            <ul className="space-y-3">
              {errors.data?.map((event) => (
                <li key={event.id} className="rounded-md border p-3 text-sm">
                  <p className="font-medium">{event.errorType} · {event.severity}</p>
                  <p className="mt-1 break-words text-muted-foreground">{event.errorMessage}</p>
                  <p className="mt-1 text-xs text-muted-foreground">{formatDate(event.createdAt)}</p>
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>
      </section>
    </main>
  );
}