uploads = []
generated = []

[[outputs]]
id = "4Jzi0J1thlJwNBEujnIj2"
uri = "file://scripts/output/codebase.pdf"
type = "pdf"
title = "MyHomeBase Codebase Export"

[[outputs]]
id = "m9B1yQ0KnpRiOfsf2RGhz"
uri = "file://scripts/output/artifacts-api-server.pdf"
type = "pdf"
title = "API Server (44 files, 2.5 MB)"

[[outputs]]
id = "qx_CjHDSXV-a_QsjNKfeA"
uri = "file://scripts/output/artifacts-myhomebase.pdf"
type = "pdf"
title = "MyHomeBase App (201 files, 3.6 MB)"

[[outputs]]
id = "6RwLAmYehEU1EKbBUAhvp"
uri = "file://scripts/output/artifacts-mockup-sandbox.pdf"
type = "pdf"
title = "Mockup Sandbox (63 files, 0.3 MB)"

[[outputs]]
id = "n3TYBQrEzp3kSncwAMI1A"
uri = "file://scripts/output/artifacts-quiz.pdf"
type = "pdf"
title = "Quiz App (63 files, 0.3 MB)"

[[outputs]]
id = "wLIU2OjlwCktYj_-M905k"
uri = "file://scripts/output/lib-db.pdf"
type = "pdf"
title = "lib/db (4 files)"

[[outputs]]
id = "IqMJImu0wvKUsH_zL6XvU"
uri = "file://scripts/output/lib-api-client-react.pdf"
type = "pdf"
title = "lib/api-client-react (2 files)"

[[outputs]]
id = "QQWUT4FsJXjaoD2qsrBHW"
uri = "file://scripts/output/lib-api-spec.pdf"
type = "pdf"
title = "lib/api-spec (1 file)"

[[outputs]]
id = "h_pnMB6tahW4qqJclD_fl"
uri = "file://scripts/output/lib-api-zod.pdf"
type = "pdf"
title = "lib/api-zod (1 file)"
