export const HOME_SYSTEMS = {
  heating: [
    { value: "gas-furnace", label: "Gas Furnace" },
    { value: "oil-furnace", label: "Oil Furnace" },
    { value: "electric-furnace", label: "Electric Furnace" },
    { value: "heat-pump", label: "Heat Pump" },
    { value: "boiler", label: "Boiler" },
    { value: "radiant-floor", label: "Radiant Floor Heating" },
    { value: "wood-stove", label: "Wood Stove/Fireplace" },
    { value: "humidifier", label: "Whole-Home Humidifier" },
  ],
  cooling: [
    { value: "central-ac", label: "Central AC" },
    { value: "window-ac", label: "Window AC Units" },
    { value: "mini-split", label: "Mini-Split System" },
    { value: "evaporative", label: "Evaporative Cooler" },
    { value: "dehumidifier", label: "Whole-Home Dehumidifier" },
    { value: "air-purifier", label: "Air Purifier / Filtration" },
  ],
  water: [
    { value: "gas-water-heater", label: "Gas Water Heater" },
    { value: "electric-water-heater", label: "Electric Water Heater" },
    { value: "tankless-gas", label: "Tankless Gas Water Heater" },
    { value: "tankless-electric", label: "Tankless Electric Water Heater" },
    { value: "solar-water", label: "Solar Water Heating" },
    { value: "well-water", label: "Well Water System" },
    { value: "water-softener", label: "Water Softener" },
    { value: "reverse-osmosis", label: "Reverse Osmosis System" },
  ],
  features: [
    { value: "solar-panels", label: "Solar Panels" },
    { value: "pool", label: "Swimming Pool" },
    { value: "spa", label: "Hot Tub/Spa" },
    { value: "generator", label: "Backup Generator" },
    { value: "septic", label: "Septic System" },
    { value: "sump-pump", label: "Sump Pump" },
    { value: "security-system", label: "Security System" },
    { value: "sprinkler-system", label: "Irrigation/Sprinkler System" },
  ],
  exterior: [
    { value: "roof-asphalt", label: "Asphalt Shingle Roof" },
    { value: "roof-metal", label: "Metal Roof" },
    { value: "roof-tile", label: "Tile / Slate Roof" },
    { value: "roof-flat", label: "Flat Roof (TPO/EPDM)" },
    { value: "gutters", label: "Gutters & Downspouts" },
    { value: "siding-vinyl", label: "Vinyl Siding" },
    { value: "siding-fibercement", label: "Fiber Cement Siding" },
    { value: "siding-wood", label: "Wood Siding" },
    { value: "windows-ext", label: "Exterior Windows" },
    { value: "entry-doors", label: "Entry Doors" },
    { value: "garage-door", label: "Garage Door" },
    { value: "deck-wood", label: "Wood Deck" },
    { value: "deck-composite", label: "Composite Deck" },
  ],
  electrical: [
    { value: "electrical-panel", label: "Electrical Panel (Breaker Box)" },
    { value: "electrical-subpanel", label: "Sub Panel" },
    { value: "surge-protector", label: "Whole-home Surge Protector" },
    { value: "ev-charger", label: "EV Charger (Level 2)" },
    { value: "smoke-co-detectors", label: "Smoke / CO Detectors" },
  ],
  structural: [
    { value: "foundation-slab", label: "Foundation (Slab)" },
    { value: "foundation-crawl", label: "Foundation (Crawl Space)" },
    { value: "foundation-basement", label: "Foundation (Full Basement)" },
    { value: "vapor-barrier", label: "Vapor Barrier" },
    { value: "radon-mitigation", label: "Radon Mitigation System" },
    { value: "waterproofing", label: "Basement Waterproofing" },
  ],
  insulation: [
    { value: "attic-insulation", label: "Attic Insulation" },
    { value: "wall-insulation", label: "Wall Insulation" },
    { value: "crawl-insulation", label: "Crawl Space Insulation" },
    { value: "attic-ventilation", label: "Attic Ventilation" },
    { value: "air-sealing", label: "Air Sealing" },
  ],
} as const;

export const HOME_SYSTEM_GROUPS = Object.entries(HOME_SYSTEMS);